### ISSUE TITLE
Make `utility` module public

### ISSUE THREAD

**Issue by multimeric** [felix-clark/ndarray-glm#22]
Currently the docs advise using `utility::one_pad` if the data doesn't have an intercept column. Unfortunately this module is also private.

**Comment by felix-clark** [comment]
Pushed to the 0.0.10 branch in ac2a424

**Comment by felix-clark** [comment]
Actually, I think `standardize` should be moved into the `utility` module as well. I'm leaning against keeping it exported in the crate namespace, I think there's more organizational consistency with having it in the `utility` namespace along with `one_pad`.

**Comment by multimeric** [comment]
That could work. You could also consider having a `prelude` module like so many other crates, which re-exports all the public APIs from miscellaneous places.

**Comment by felix-clark** [comment]
> That could work. You could also consider having a `prelude` module like so many other crates, which re-exports all the public APIs from miscellaneous places.

Opened issue #23 to consider this
